### ISSUE TITLE
KeyError when preparing `Synapse` object

### ISSUE THREAD

**Issue by paulbrodersen** [brian-team/brian2#1007]
This is a terrible error report, my apologies upfront. I have tried making several MWEs that reproduce the behaviour but without any success: if I make the models any simpler, everything works just fine.
I am hence posting the full script and error log, in the hope that somebody will take pity and have a look at it anyway.

## Background

I am trying to implement the model in [this paper](https://arxiv.org/abs/1705.11146), specifically figure 2.
In the script below, all constants are named exactly as in the paper with the exception that I replaced (variable, \hat{variable}) pairs with (variable1, variable2) name pairs.

## Problem description

The offending line is l. 90 in the synapse model:

```
w         += r * error_post * sigma_post * z2
```

If I remove this line, everything runs just fine, apart from the fact that obviously the weights are not updated. When this line is included in the script, I get the following error (log file attached and linked below):

```python
  File "superspike_script.py", line 155, in <module>
    b2.run(simulation_time)
  File "/home/paul/src/brian2/brian2/units/fundamentalunits.py", line 2375, in new_f
    result = f(*args, **kwds)
  File "/home/paul/src/brian2/brian2/core/magic.py", line 371, in run
    namespace=namespace, profile=profile, level=2+level)
  File "/home/paul/src/brian2/brian2/core/magic.py", line 231, in run
    namespace=namespace, profile=profile, level=level+1)
  File "/home/paul/src/brian2/brian2/core/base.py", line 276, in device_override_decorated_function
    return func(*args, **kwds)
  File "/home/paul/src/brian2/brian2/units/fundamentalunits.py", line 2375, in new_f
    result = f(*args, **kwds)
  File "/home/paul/src/brian2/brian2/core/network.py", line 951, in run
    self.before_run(namespace)
  File "/home/paul/src/brian2/brian2/core/base.py", line 276, in device_override_decorated_function
    return func(*args, **kwds)
  File "/home/paul/src/brian2/brian2/core/network.py", line 843, in before_run
    raise brian_object_exception("An error occurred when preparing an object.", obj, ex)
BrianObjectException: Original error and traceback:
Traceback (most recent call last):
  File "/home/paul/src/brian2/brian2/core/network.py", line 841, in before_run
    obj.before_run(run_namespace)
  File "/home/paul/src/brian2/brian2/core/base.py", line 276, in device_override_decorated_function
    return func(*args, **kwds)
  File "/home/paul/src/brian2/brian2/synapses/synapses.py", line 298, in before_run
    CodeRunner.before_run(self, run_namespace)
  File "/home/paul/src/brian2/brian2/groups/group.py", line 1115, in before_run
    codeobj_class=self.codeobj_class
  File "/home/paul/src/brian2/brian2/codegen/codeobject.py", line 240, in create_runner_codeobj
    run_namespace=run_namespace)
  File "/home/paul/src/brian2/brian2/groups/group.py", line 739, in resolve_all
    run_namespace=run_namespace)
  File "/home/paul/src/brian2/brian2/groups/group.py", line 696, in _resolve
    return self._resolve_external(identifier, run_namespace=run_namespace)
  File "/home/paul/src/brian2/brian2/groups/group.py", line 807, in _resolve_external
    (identifier))
KeyError: 'The identifier "beta" could not be resolved.'

Error encountered with object named "synapses_pre".
Object was created here (most recent call only, full details in debug log):
  File "superspike_script.py", line 101, in <module>
    connections = b2.Synapses(input_neurons, output_neurons, **synapse_kwargs)

An error occurred when preparing an object. KeyError: 'The identifier "beta" could not be resolved.'
```

As far as I can see, the problem is that `sigma_post` is itself is an expression:

```python
h = beta * (U - U_rest)                : 1
sigma = 1. / (1 + abs(h))**2           : 1
```

`U` and `U_rest` are the membrane potential and the resting membrane potential respectively; `U` is defined through a differential equation, `U_rest` is a constant with `U_rest = -60 * b2.mvolt`; beta is also a constant with `beta = 1. / b2.mvolt`.
At the moment, the parser reports that it fails to resolve `beta`. However, if I replace `beta` in the expression with `mvolt ** -1` or `1. / mvolt`, the parser then complains about `U_rest`. I hence think that there is a deeper issue here.

Again, apologies for the lack of MWE. Any insight in how to remedy the situation would be appreciated.

## Script

```
#!/usr/bin/env python

"""
Implementation of Zenke & Ganguli (2017) SuperSpike, Fig 2
"""

import numpy as np
import matplotlib.pyplot as plt
import brian2 as b2

from copy import deepcopy

# --------------------------------------------------------------------------------

b2.start_scope()

# create 100 input neurons and 1 output neuron

model = '''
dU/dt = (U_rest - U + I_syn) / tau_m   : volt (unless refractory)
dI_syn/dt = - I_syn / tau_syn          : volt
h = beta * (U - U_rest)                : 1
sigma = 1. / (1 + abs(h))**2           : 1
'''

# NB: this is not like in the paper, where errors are cleared periodically
input_neuron_model = model + '''
derror/dt = -error / tau_m             : 1
'''

output_neuron_model = model + '''
dalphaS1/dt = -alphaS1 / tau_m         : 1
dalphaS2/dt = -alphaS2 / tau_m         : 1
error = alphaS2 - alphaS1              : 1
'''

namespace = dict(
    U_rest   =  -60. * b2.mvolt,   # Resting potential
    U_thresh =  -50. * b2.mvolt,   # Spike threshold
    tau_m    =   10. * b2.msecond, # Membrane time constrant
    tau_syn  =    5. * b2.msecond, # Synaptic decay time
    beta     =    1. / b2.mvolt,   #
)

neuron_kwargs = dict(
    model      = input_neuron_model,
    namespace  = namespace,
    threshold  = 'U > U_thresh',
    reset      = 'U = U_rest',
    refractory = 5 * b2.ms,
    method     = 'euler',
)

output_neuron_kwargs = deepcopy(neuron_kwargs)
output_neuron_kwargs['model'] = output_neuron_model
output_neuron_kwargs['reset'] = '''
U = U_rest
alphaS1 += 1
'''

total_inputs  = 100
total_targets = 1
input_neurons  = b2.NeuronGroup(N=total_inputs, **neuron_kwargs)
output_neurons = b2.NeuronGroup(N=total_targets, **output_neuron_kwargs)

# --------------------------------------------------------------------------------
# randomise initial membrane voltages

# TODO: debug; potentially because brian magic does not know about U_thresh?
# input_neurons.U  = 'U_rest + (U_thresh - U_rest) * rand()'
# output_neurons.U = 'U_rest + (U_thresh - U_rest) * rand()'

input_neurons.U  = -60. * b2.mvolt
output_neurons.U = -60. * b2.mvolt

# --------------------------------------------------------------------------------

# connect input neurons to the output neuron(s)

synapse_kwargs = dict(
    model = '''
    w                                : volt
    dz1/dt = - z1 / tau_rise         : 1 (event-driven)
    dz2/dt = (- z2 + z1) / tau_decay : 1 (event-driven)
    ''',
    on_pre = '''
    I_syn     += w
    z1        += 1
    error_pre += w / mvolt * error_post
    w         += r * error_post * sigma_post * z2
    ''',
    namespace = dict(
        tau_rise  =  5. * b2.msecond, # PSP rise time
        tau_decay = 10. * b2.msecond, # PSP decay time
        r         =  1. * b2.mvolt,   # learning rate
    ),
    delay = 0.8 * b2.msecond,
)


connections = b2.Synapses(input_neurons, output_neurons, **synapse_kwargs)
connections.connect(p=1.0) # i.e. fully connected
connections.w = 10. * b2.mvolt # TODO: set initial weight such that input to output neuron is subthreshold but maximal

# --------------------------------------------------------------------------------
# create 100 Poisson input spike trains, each 500 ms long;
# rate is not mentioned in the paper; assuming 10 Hz (i.e. the target rate)

firing_rate       = 5. / b2.second
simulation_time   = 0.5 * b2.second
spikes_per_neuron = firing_rate * simulation_time
total_spikes      = total_inputs * spikes_per_neuron
times             = np.sort(np.random.rand(total_inputs)) * simulation_time
indices           = np.random.randint(total_inputs, size=len(times))

generators = b2.SpikeGeneratorGroup(total_inputs, indices, times)
generator_synapses = b2.Synapses(generators, input_neurons,
                                 model  = '''w : volt''',
                                 on_pre = '''I_syn_post += w''')
generator_synapses.connect(condition='i==j')
generator_synapses.w = 40. * b2.mvolt # TODO: figure out why this is not the difference between U_thresh and U_rest, i.e. 10 mV

# create 1 target spike train with 5 spikes equally spaced across simulation time

times = simulation_time * np.linspace(0., 1., 5)
indices = np.zeros((len(times)))

# pad at the ends while keeping simulation time constant
times *= 0.8 # compress
times += 0.1 * simulation_time # shift forward

target_generators = b2.SpikeGeneratorGroup(total_targets, indices, times)
target_generator_synapses = b2.Synapses(target_generators, output_neurons,
                                        model = '''w : 1''',
                                        on_pre = '''alphaS2 += w''')
target_generator_synapses.connect(condition='i==j')
target_generator_synapses.w = 1.

# --------------------------------------------------------------------------------
# setup state and spike monitors

generator_spike_monitor = b2.SpikeMonitor(generators)
input_spike_monitor     = b2.SpikeMonitor(input_neurons)
output_spike_monitor    = b2.SpikeMonitor(output_neurons)
target_spike_monitor    = b2.SpikeMonitor(target_generators)

input_variables = ['U', 'I_syn', 'sigma', 'error']
output_variables = input_variables + ['alphaS1', 'alphaS2']
input_state_monitor  = b2.StateMonitor(input_neurons,  input_variables, record=True)
output_state_monitor = b2.StateMonitor(output_neurons, output_variables, record=True)

# --------------------------------------------------------------------------------
# run simulation

b2.run(simulation_time)

# --------------------------------------------------------------------------------
# make plots

fig, axes = plt.subplots(len(input_variables), 1, sharex=True)
for ax, var in zip(axes, input_variables):
    ax.plot(input_state_monitor.t / b2.ms, eval('input_state_monitor.' + var + '_.T'))
    ax.set_ylabel(var)
ax.set_xlabel('time [ms]')

fig, axes = plt.subplots(len(output_variables), 1, sharex=True)
for ax, var in zip(axes, output_variables):
    ax.plot(output_state_monitor.t / b2.ms, eval('output_state_monitor.' + var + '_.T'))
    ax.set_ylabel(var)
ax.set_xlabel('time [ms]')

spike_monitors = [('generators' , generator_spike_monitor),
                  ('inputs'     , input_spike_monitor),
                  ('outputs'    , output_spike_monitor),
                  ('targets'    , target_spike_monitor)]

fig, axes = plt.subplots(len(spike_monitors), 1, sharex=True)
for (label, monitor), ax in zip(spike_monitors, axes):
    times = monitor.t / b2.ms
    senders = monitor.i
    ax.plot(times, senders, '.k', markersize=5.)
    ax.set_ylabel(label)

plt.show()
```

## Log file 
[brian_debug_rnOnOO.log](https://github.com/brian-team/brian2/files/2367531/brian_debug_rnOnOO.log)

**Comment by mstimberg** [comment]
[In the future, please direct questions or error reports where you are not sure whether it is "Brian's fault" to Brian's [support mailing list](https://groups.google.com/forum/#!forum/briansupport) (briansupport@googlegroups.com), we try to keep the github issues for bugs and feature requests.]

Hi @paulbrodersen . This is indeed not very clear, we should communicate this better: "subexpressions" like `sigma` in your example are just placeholders; when you refer to them, they get replaced by their expressions (with the correct indexing and some renaming to avoid name clashes). In your case, this means that it needs access to the parameters `beta` and `U_rest` from within the `Synapses` object. This would not be a problem when using parameters directly defined as variables in the surrounding code. In your case, you specify explicit namespaces, though, and the namespace for the `Synapses` object does not contain `beta` nor `U_rest`. When adding them to the namespace, your  simulation runs.

PS: If this example runs and indeed reproduces one or more figures from the SuperSpike paper, please consider submitting it as an example for the documentation :bowing_man:

**Comment by paulbrodersen** [comment]
1) Thanks for the quick reply. Much appreciated. Your fix works (obviously), and I think I have a better understanding of how the namespaces and equations are handled. Again, much obliged. 

2) I just joined the mailing list. I will keep the issue list clean(er) in the future. On that note: do you guys also want a StackOverflow tag for user questions such as mine, or would you rather keep everything bundled in the mailing list? 

3) I will submit a PR with an additional entry in `examples/frompapers/` once I have it fully figured out. I need to work on a different project the next two weeks but then I should have time to play with this stuff again. It's a good paper, and there is also a [repo](https://github.com/fzenke/pub2018superspike) with the original implementation, so I should be able to figure it out.
