### ISSUE TITLE
run() error-BrianObjectException

### ISSUE THREAD

**Issue by DimChatz** [brian-team/brian2#1032]
Hello guys I am trying to create an Izhikevich simple model neuron so I created the following code:

```
from brian2 import *
import numpy as np
%matplotlib inline

#========================================================
#THIS CODE IS FOR CREATING AN IZHIKEVICH RESONATOR NEURON
#========================================================

start_scope()

#DECLARATION OF CONSTANTS FOR THE NEURON MODEL
C=1*pfarad
a=0.6/msecond
b=0.8*pamp/mvolt
Vreset=-45*mvolt
Vpeak=50*mvolt #arbitrary-do we need this?
Vrest=-70*mvolt  #arbitrary
Vthresh=-35*mvolt #arbitrary
k=0.7*pamp/mvolt/mvolt #arbitrary
d=-20*pamp

Imean=15.4
sigma=0.3

#Gaussian distribution of current
Iin=np.random.normal(Imean,sigma)
Iin=Iin*pamp

#EQUATIONS OF NEURON
eqs='''
dV/dt=1/C*(k*(V-Vrest)*(V-Vthresh)-u+Iin) : volt
du/dt=a*(b*(V-Vrest)-u) : amp
'''

defaultclock.dt = 0.1*ms

#creation of neuron
G=NeuronGroup(1,eqs,threshold='V=Vthresh',reset='V>Vpeak,V=Vreset',method='euler')

#TESTING
M = StateMonitor(G, 'V', record=True)

G.V = -30*mvolt # initial value

run(600*ms)

plot(M.t/ms, M.V[0])
xlabel('Time (ms)')
ylabel('V')
```

but i get this errors (which i don't get when i comment out the run() command

``` 
Traceback (most recent call last):

  File "/home/tzikos/anaconda3/lib/python3.6/site-packages/IPython/core/interactiveshell.py", line 3267, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)

  File "<ipython-input-4-ad1c754ecb3c>", line 45, in <module>
    run(600*ms)

  File "/home/tzikos/anaconda3/lib/python3.6/site-packages/brian2/units/fundamentalunits.py", line 2375, in new_f
    result = f(*args, **kwds)

  File "/home/tzikos/anaconda3/lib/python3.6/site-packages/brian2/core/magic.py", line 371, in run
    namespace=namespace, profile=profile, level=2+level)

  File "/home/tzikos/anaconda3/lib/python3.6/site-packages/brian2/core/magic.py", line 231, in run
    namespace=namespace, profile=profile, level=level+1)

  File "/home/tzikos/anaconda3/lib/python3.6/site-packages/brian2/core/base.py", line 276, in device_override_decorated_function
    return func(*args, **kwds)

  File "/home/tzikos/anaconda3/lib/python3.6/site-packages/brian2/units/fundamentalunits.py", line 2375, in new_f
    result = f(*args, **kwds)

  File "/home/tzikos/anaconda3/lib/python3.6/site-packages/brian2/core/network.py", line 951, in run
    self.before_run(namespace)

  File "/home/tzikos/anaconda3/lib/python3.6/site-packages/brian2/core/base.py", line 276, in device_override_decorated_function
    return func(*args, **kwds)

  File "/home/tzikos/anaconda3/lib/python3.6/site-packages/brian2/core/network.py", line 843, in before_run
    raise brian_object_exception("An error occurred when preparing an object.", obj, ex)

  File "<string>", line unknown
BrianObjectException
```

can you please help me ? I do not know why this happens nor how to fix it

**Comment by mstimberg** [comment]
See my reply on the mailing list: https://groups.google.com/d/topic/brian-development/dnaZ4i2USxE/discussion

PS: `run` triggers this error (and many other types of errors), because only at this point Brian knows about all constants, objects, etc. and prepares the network by checking the correctness of equations etc.
