### ISSUE TITLE
unexpected error

### ISSUE THREAD

**Issue by vslobody** [brian-team/brian2#1046]
trying to run example from Example: opencv_movie and getting the following message:

`ERROR      Brian 2 encountered an unexpected error. If you think this is bug in Brian 2, please report this issue either to the mailing list at <http://groups.google.com/group/brian-development/>, or to the issue tracker at <https://github.com/brian-team/brian2/issues>. Please include this file with debug information in your report: /tmp/brian_debug_J_JmwM.log  Additionally, you can also include a copy of the script that was run, available at: /tmp/brian_script__VM1Vg.py Thanks! [brian2]`

adding files as suggested in the message

[brian_debug_J_JmwM.log](https://github.com/brian-team/brian2/files/2775263/brian_debug_J_JmwM.log)

**Comment by mstimberg** [comment]
Closing this due to lack of response, feel free to reopen the issue if there is still something unclear.

Also note that [the example](https://brian2.readthedocs.io/en/stable/examples/advanced.opencv_movie.html) has been updated for newer versions of OpenCV.

**Comment by yahya-ashrafi** [comment]
from brian2 import *
from brian2 import tanh
import numpy as np
start_scope()

num_neurons = 1
duration = 50*ms

# Parameters
area = 20000*umetre**2
Cm = 1*ufarad*cm**-2 * area
gl = 0.02*msiemens*cm**-2*area # ms/cm**2
El = -50.0*mV # mV
EK = -90.0*mV # mV
ENa = 55.0*mV # mV
g_na = 150.0*msiemens*cm**-2*area # ms/cm**2  
g_kd = 0.4*msiemens*cm**-2*area # ms/cm**2

# The model
eqs = Equations('''
dv/dt = (gl*(El-v) - g_na*(m*m*m)*h*(v-ENa) - g_kd*(n*n*n*n)*(v-EK) + I)/Cm : volt
dm/dt = 0.32*(mV**-1)*4*mV/exprel((13.*mV-v)/(4*mV))/ms*(1-m)-0.28*(mV**-1)*5*mV/exprel((v-40.*mV)/(5*mV))/ms*m : 1
dn/dt = (0.5/mV)*(1*mV-(np.tanh((100*mV-v)/70)))/ms*(1.-n)-((2)/2)*(1+np.tanh(-(30*mV+v)/15*mV))/ms*n : 1
dh/dt = 0.128*exp((17.*mV-v)/(18.*mV))/ms*(1.-h)-4./(1+exp((40.*mV-v)/(5.*mV)))/ms*h : 1
I : amp
''')
# Threshold and refractoriness are only used for spike counting
group = NeuronGroup(num_neurons, eqs,
                    refractory = 5*ms,
                    method='exponential_euler')
group.v = 'rand()*mV'
group.I = 0.4*nA #'0.7*nA * i / num_neurons'
M = StateMonitor(group, 'v', record=True)
run(duration)





this is the output that have a lots of problem I didn't know that how can I solve that. what I thinks that is all problem for existence of tanh but why?
ERROR      Brian 2 encountered an unexpected error. If you think this is a bug in Brian 2, please report this issue either to the discourse forum at <http://brian.discourse.group/>, or to the issue tracker at <https://github.com/brian-team/brian2/issues>. Please include this file with debug information in your report: C:\Users\Dell\AppData\Local\Temp\brian_debug_mux8u38e.log  Additionally, you can also include a copy of the script that was run, available at: C:\Users\Dell\AppData\Local\Temp\brian_script_cms_gpkg.py Thanks! [brian2]
Traceback (most recent call last):
  File "C:\Users\Dell\AppData\Local\Programs\Python\Python310\lib\site-packages\brian2\parsing\rendering.py", line 78, in render_node
    return getattr(self, methname)(node)
  File "C:\Users\Dell\AppData\Local\Programs\Python\Python310\lib\site-packages\brian2\parsing\rendering.py", line 238, in render_Call
    return self.render_func(node.func)(*(self.render_node(arg)
  File "C:\Users\Dell\AppData\Local\Programs\Python\Python310\lib\site-packages\brian2\parsing\rendering.py", line 217, in render_func
    if node.id in DEFAULT_FUNCTIONS:
AttributeError: 'Attribute' object has no attribute 'id'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\Users\Dell\Desktop\dopamin.py", line 21, in <module>
    eqs = Equations('''
  File "C:\Users\Dell\AppData\Local\Programs\Python\Python310\lib\site-packages\brian2\equations\equations.py", line 554, in __init__
    self._equations = parse_string_equations(eqns)
  File "C:\Users\Dell\AppData\Local\Programs\Python\Python310\lib\site-packages\brian2\utils\caching.py", line 101, in cached_func
    func._cache[cache_key] = func(*args, **kwds)
  File "C:\Users\Dell\AppData\Local\Programs\Python\Python310\lib\site-packages\brian2\equations\equations.py", line 366, in parse_string_equations
    expression = Expression(p.sub(' ', expression))
  File "C:\Users\Dell\AppData\Local\Programs\Python\Python310\lib\site-packages\brian2\equations\codestrings.py", line 107, in __init__
    str_to_sympy(code)
  File "C:\Users\Dell\AppData\Local\Programs\Python\Python310\lib\site-packages\brian2\parsing\sympytools.py", line 76, in str_to_sympy
    return _str_to_sympy(expr)
  File "C:\Users\Dell\AppData\Local\Programs\Python\Python310\lib\site-packages\brian2\utils\caching.py", line 101, in cached_func
    func._cache[cache_key] = func(*args, **kwds)
  File "C:\Users\Dell\AppData\Local\Programs\Python\Python310\lib\site-packages\brian2\parsing\sympytools.py", line 82, in _str_to_sympy
    s_expr = SympyNodeRenderer().render_expr(expr)
  File "C:\Users\Dell\AppData\Local\Programs\Python\Python310\lib\site-packages\brian2\parsing\rendering.py", line 66, in render_expr
    return self.render_node(node.body)
  File "C:\Users\Dell\AppData\Local\Programs\Python\Python310\lib\site-packages\brian2\parsing\rendering.py", line 78, in render_node
    return getattr(self, methname)(node)
  File "C:\Users\Dell\AppData\Local\Programs\Python\Python310\lib\site-packages\brian2\parsing\rendering.py", line 282, in render_BinOp
    return op(self.render_node(node.left),
  File "C:\Users\Dell\AppData\Local\Programs\Python\Python310\lib\site-packages\brian2\parsing\rendering.py", line 78, in render_node
    return getattr(self, methname)(node)
  File "C:\Users\Dell\AppData\Local\Programs\Python\Python310\lib\site-packages\brian2\parsing\rendering.py", line 286, in render_BinOp
    return op(self.render_node(node.left), self.render_node(node.right))
  File "C:\Users\Dell\AppData\Local\Programs\Python\Python310\lib\site-packages\brian2\parsing\rendering.py", line 78, in render_node
    return getattr(self, methname)(node)
  File "C:\Users\Dell\AppData\Local\Programs\Python\Python310\lib\site-packages\brian2\parsing\rendering.py", line 273, in render_BinOp
    return op(self.render_node(node.left),
  File "C:\Users\Dell\AppData\Local\Programs\Python\Python310\lib\site-packages\brian2\parsing\rendering.py", line 78, in render_node
    return getattr(self, methname)(node)
  File "C:\Users\Dell\AppData\Local\Programs\Python\Python310\lib\site-packages\brian2\parsing\rendering.py", line 286, in render_BinOp
    return op(self.render_node(node.left), self.render_node(node.right))
  File "C:\Users\Dell\AppData\Local\Programs\Python\Python310\lib\site-packages\brian2\parsing\rendering.py", line 78, in render_node
    return getattr(self, methname)(node)
  File "C:\Users\Dell\AppData\Local\Programs\Python\Python310\lib\site-packages\brian2\parsing\rendering.py", line 283, in render_BinOp
    -self.render_node(node.right))
  File "C:\Users\Dell\AppData\Local\Programs\Python\Python310\lib\site-packages\brian2\parsing\rendering.py", line 80, in render_node
    raise SyntaxError(f"Unknown syntax: {nodename}")
SyntaxError: Unknown syntax: Call
