### ISSUE TITLE
test suite fails due to wrong GSL version

### ISSUE THREAD

**Issue by paulbrodersen** [brian-team/brian2#1097]
I just installed brian2 using `pip` on Ubuntu 18.04 LST in a clean virtual environment and the test suite failed with the following error message:

```shell 
WARNING    Integrating equations with GSL is still considered experimental [brian2.stateupdaters.GSL]
/home/paul/.cython/brian_extensions/_cython_magic_c1edacdc60b453c9f0819f4d0d75e3ea.cpp:662:10: fatal error: gsl/gsl_odeiv2.h: No such file or directory
 #include "gsl/gsl_odeiv2.h"
          ^~~~~~~~~~~~~~~~~~
compilation terminated.
E/home/paul/.cython/brian_extensions/_cython_magic_f61362f745cb16f8ce6ba3ba81bede7e.cpp:662:10: fatal error: gsl/gsl_odeiv2.h: No such file or directory
 #include "gsl/gsl_odeiv2.h"
          ^~~~~~~~~~~~~~~~~~
compilation terminated.
E/home/paul/.cython/brian_extensions/_cython_magic_3e1e53d7736b35080d23759bbc2b4101.cpp:662:10: fatal error: gsl/gsl_odeiv2.h: No such file or directory
 #include "gsl/gsl_odeiv2.h"
  File "/home/paul/.virtualenvs/brian/lib/python3.6/site-packages/brian2/codegen/runtime/cython_rt/cython_rt.py", line 147, in compile
    sources=self.sources
  File "/home/paul/.virtualenvs/brian/lib/python3.6/site-packages/brian2/codegen/runtime/cython_rt/extension_manager.py", line 138, in create_extension
    sources=sources)
  File "/home/paul/.virtualenvs/brian/lib/python3.6/site-packages/brian2/codegen/runtime/cython_rt/extension_manager.py", line 280, in _load_module
    self._build_extensions_serial()
  File "/usr/lib/python3.6/distutils/command/build_ext.py", line 473, in _build_extensions_serial
    self.build_extension(ext)
  File "/usr/lib/python3.6/distutils/command/build_ext.py", line 533, in build_extension
    depends=ext.depends)
  File "/usr/lib/python3.6/distutils/ccompiler.py", line 574, in compile
    raise CompileError(msg)
distutils.errors.CompileError: command 'x86_64-linux-gnu-gcc' failed with exit status 1
Traceback (most recent call last):
  File "/home/paul/.virtualenvs/brian/lib/python3.6/site-packages/brian2/core/network.py", line 841, in before_run
    obj.before_run(run_namespace)
  File "/home/paul/.virtualenvs/brian/lib/python3.6/site-packages/brian2/groups/group.py", line 1128, in before_run
    codeobj_class=self.codeobj_class
  File "/home/paul/.virtualenvs/brian/lib/python3.6/site-packages/brian2/codegen/codeobject.py", line 416, in create_runner_codeobj
    compiler_kwds=compiler_kwds
  File "/home/paul/.virtualenvs/brian/lib/python3.6/site-packages/brian2/devices/device.py", line 326, in code_object
    codeobj.compile()
  File "/home/paul/.virtualenvs/brian/lib/python3.6/site-packages/brian2/codegen/runtime/GSLcython_rt/GSLcython_rt.py", line 43, in compile
    raise GSLCompileError(("\nCompilation of files generated for integration with GSL has failed."
brian2.codegen.runtime.GSLcython_rt.GSLcython_rt.GSLCompileError: 

Error encountered with object named "neurongroup_1_stateupdater".
An error occurred when preparing an object. brian2.codegen.runtime.GSLcython_rt.GSLcython_rt.GSLCompileError: 
Compilation of files generated for integration with GSL has failed.
One cause for this could be incorrect installation of GSL itself.
```

I fixed the issue by installing the development version of GSL:

```shell
sudo apt install libgsl-dev
```

I might be good to add a remark to the installation instructions regarding the GSL installation; otherwise, feel free to close.

**Comment by mstimberg** [comment]
Hi, thanks for the report. I agree that we should add this information to the documentation. We generally recommend the installation via conda which will automatically install the GSL as a dependency, but for the installation from source we should definitely mention this. Somewhat related: the GSL is an optional dependency, it would be better if the test suite did not fail if it isn't installed (or e.g. make testing the GSL optional).

**Comment by shivChitinous** [comment]
I had the same issue on macOSx high sierra. Any idea how to solve the issue in this case? I couldn't find a way to install the development version of gsl on macOS.

**Comment by mstimberg** [comment]
You can try to install the GSL as described here: https://gist.github.com/TysonRayJones/af7bedcdb8dc59868c7966232b4da903#osx

But again, GSL is *optional*, you only need it if you want to use on of the [integration methods provided by the GSL](https://brian2.readthedocs.io/en/stable/user/numerical_integration.html#gsl-stateupdaters). Brian runs perfectly fine without it.
