### ISSUE TITLE
Equation definition is difficult to format with current Python tools

### ISSUE THREAD

**Issue by SS88** [brian-team/brian2#1198]
I am using Brian2 to define this equation : 

```
eqs = """ dv/dt  = k(v-Vr)(v-Vt)/C -u/C + I/C: volt
                            du/dt = a(bv-u): volt"""
```

And then call it in a NeuronGroup definition like this : 

```
P = NeuronGroup(N, eqs, threshold='v>Vt', reset='v = Vr', refractory=5*ms,
                method='exact')
```

But i'm getting an error on the definition syntax : 
```
ERROR      Brian 2 encountered an unexpected error. If you think this is bug in Brian 2, please report this issue either to the mailing list at <http://groups.google.com/group/brian-development/>, or to the issue tracker at <https://github.com/brian-team/brian2/issues>. Please include this file with debug information in your report: C:\Users\iteslab\AppData\Local\Temp\brian_debug_eqxeqk_n.log  Additionally, you can also include a copy of the script that was run, available at: C:\Users\iteslab\AppData\Local\Temp\brian_script_uiwzzsdp.py Thanks! [brian2]
Traceback (most recent call last):
  File "C:\Users\iteslab\AppData\Local\Programs\Python\Python37\lib\site-packages\brian2\parsing\rendering.py", line 79, in render_node
    return getattr(self, methname)(node)
  File "C:\Users\iteslab\AppData\Local\Programs\Python\Python37\lib\site-packages\brian2\parsing\rendering.py", line 243, in render_Call
    return self.render_func(node.func)(*(self.render_node(arg)
  File "C:\Users\iteslab\AppData\Local\Programs\Python\Python37\lib\site-packages\brian2\parsing\rendering.py", line 222, in render_func
    if node.id in DEFAULT_FUNCTIONS:
AttributeError: 'Call' object has no attribute 'id'
```
Please let me know what's missing and how to format equations for Brian2.

**Comment by Vigneswaran-Chandrasekaran** [comment]
Hi, to define multiplication operation `*` operator should be used

**Comment by mstimberg** [comment]
As @Vigneswaran-Chandrasekaran said, equations mostly use Python syntax (see the [documentation](https://brian2.readthedocs.io/en/stable/user/equations.html#arithmetic-operations-and-functions)). You get the error message (which admittedly should be improved) because `k(v-Vr)(v-Vt)` is interpreted as two function calls, it should be `k*(v-Vr)*(v-Vt)` instead.
