### ISSUE TITLE
IndexError for integers in generated equations code

### ISSUE THREAD

**Issue by spokli** [brian-team/brian2#1199]
**Issue:** An integer index of a TimedArray is translated to a float during code generation.

```python
import numpy as np
from brian2 import *
prefs.codegen.target = 'cython' # weave, cython, numpy

net = Network()

I = TimedArray(np.random.rand(10, 5) * pA, dt=defaultclock.dt)

# THIS IS THE PROBLEM LINE
eqs = 'dv/dt = (150*Mohm)/(15*ms) * I(t, ' + str(2) + ' + i) : volt'

print 'equation: \n', eqs

G = NeuronGroup(1, 
                eqs, 
                threshold='v > -40*mvolt',
                reset='v = -70*mvolt', 
                method='euler')
    
G.v = -70*mvolt
net.add(G)
    
# Run the network
net.run(1*second)
```

The printed equations still use the integer 2:

> equation: 
> dv/dt = (150*Mohm)/(15*ms) * I(t, 2 + i) : volt

**Error text with Cython code generation**
```
Error compiling Cython file:
------------------------------------------------------------
...
    for _idx in range(N):
        _vectorisation_idx = _idx
                
        i = _array_neurongroup_1_i[_idx]
        v = _array_neurongroup_1_v[_idx]
        _v = (_lio_1 * _timedarray_1(t, 2.0 + i)) + v
                                           ^
------------------------------------------------------------

~/.cython/brian_extensions/_cython_magic_e49d15cd74f3430d82cb4827b33757a7.pyx:118:44: Cannot assign type 'double' to 'const int'```
```

**Error text with numpy code generation**
```
BrianObjectException: Original error and traceback:
Traceback (most recent call last):
  File "miniconda2/envs/brian/lib/python2.7/site-packages/brian2/codegen/runtime/numpy_rt/numpy_rt.py", line 246, in run
    exec(self.compiled_code, self.namespace)
  File "(string)", line 19, in <module>
  File "miniconda2/envs/brian/lib/python2.7/site-packages/brian2/input/timedarray.py", line 230, in unitless_timed_array_func
    return values[timestep, i]
IndexError: arrays used as indices must be of integer (or boolean) type

Error encountered with object named "neurongroup".
Object was created here (most recent call only, full details in debug log):
  File "<ipython-input-6-321ca0774a4a>", line 18, in <module>
    method='euler')

An exception occured during the execution of code object neurongroup_stateupdater_codeobject.
The error was raised in the following line:
_v = (_lio_1 * I(t, 2.0 + i)) + v
 IndexError: arrays used as indices must be of integer (or boolean) type
(See above for original error message and traceback.)
```

To answer the question 'why would you do that?' in advance: I created a 2D `TimedArray` as noise current for each timestep and each neuron. The neurons are organised in different layers, so I need an index per layer and neuron:
```python
import numpy as np
from brian2 import *
prefs.codegen.target = 'cython' # weave, cython, numpy

num_layers = 2
num_neurons_per_layer = 3
num_time_steps = 10000

net = Network()

# Prepare input currents for each timestep for each neuron.
# First dimension = timestep
# Second dimension = total number of neurons
I = TimedArray(np.random.rand(num_time_steps, num_layers * num_neurons_per_layer) * pA, dt=defaultclock.dt)

# Create layers
for layer_id in range(num_layers):
    
    # THIS IS THE PROBLEM LINE
    eqs = 'dv/dt = (150*Mohm)/(15*ms) * I(t, ' + str(layer_id * num_neurons_per_layer) + ' + i) : volt'
    print 'equation: \n', eqs

    new_layer = NeuronGroup(num_neurons_per_layer, 
                            eqs, 
                            threshold='v > -40*mvolt',
                            reset='v = -70*mvolt', 
                            method='euler')
    
    new_layer.v = -70*mvolt
    net.add(new_layer)
    
# Run the network
net.run(1*second)
```
**Environment**
Python 2.7
<details>
  <summary>Click to get installed packages info</summary>
  <p>

```
_libgcc_mutex             0.1                 conda_forge    conda-forge
_openmp_mutex             4.5                      1_llvm    conda-forge
attrs                     19.3.0                     py_0    conda-forge
backports                 1.0                        py_2    conda-forge
backports.functools_lru_cache 1.6.1                      py_0    conda-forge
backports.shutil_get_terminal_size 1.0.0                      py_3    conda-forge
backports_abc             0.5                        py_1    conda-forge
binutils_impl_linux-64    2.34                 h53a641e_5    conda-forge
binutils_linux-64         2.34                hc952b39_20    conda-forge
bleach                    3.1.5              pyh9f0ad1d_0    conda-forge
brian2                    2.3              py27hc9558a2_0    conda-forge
ca-certificates           2020.6.20            hecda079_0    conda-forge
certifi                   2019.11.28       py27h8c360ce_1    conda-forge
configparser              3.7.3            py27h8c360ce_2    conda-forge
cycler                    0.10.0                     py_2    conda-forge
cython                    0.29.15          py27haf22ab1_1    conda-forge
dbus                      1.13.6               he372182_0    conda-forge
decorator                 4.4.2                      py_0    conda-forge
defusedxml                0.6.0                      py_0    conda-forge
entrypoints               0.3             py27h8c360ce_1001    conda-forge
enum34                    1.1.10           py27h8c360ce_1    conda-forge
expat                     2.2.9                he1b5a44_2    conda-forge
fastcache                 1.1.0            py27hdf8410d_1    conda-forge
fontconfig                2.13.1            h86ecdb6_1001    conda-forge
freetype                  2.10.2               he06d7ca_0    conda-forge
functools32               3.2.3.2                    py_3    conda-forge
future                    0.18.2           py27h8c360ce_1    conda-forge
futures                   3.3.0            py27h8c360ce_1    conda-forge
gcc_impl_linux-64         7.5.0                hd420e75_6    conda-forge
gcc_linux-64              7.5.0               h09487f9_20    conda-forge
gettext                   0.19.8.1          hc5be6a0_1002    conda-forge
glib                      2.64.3               h6f030ca_0    conda-forge
gmp                       6.2.0                he1b5a44_2    conda-forge
gmpy2                     2.1.0b1          py27h04dde30_0    conda-forge
gsl                       2.6                  h294904e_0    conda-forge
gst-plugins-base          1.14.5               h0935bb2_2    conda-forge
gstreamer                 1.14.5               h36ae1b5_2    conda-forge
gxx_impl_linux-64         7.5.0                hdf63c60_6    conda-forge
gxx_linux-64              7.5.0               h09487f9_20    conda-forge
icu                       64.2                 he1b5a44_1    conda-forge
ipykernel                 4.10.0                   py27_1    conda-forge
ipyparallel               6.2.4            py27h8c360ce_0    conda-forge
ipython                   5.8.0                    py27_1    conda-forge
ipython_genutils          0.2.0                      py_1    conda-forge
ipywidgets                7.5.1                      py_0    conda-forge
jinja2                    2.11.2             pyh9f0ad1d_0    conda-forge
jpeg                      9d                   h516909a_0    conda-forge
jsonschema                3.0.2                    py27_0    conda-forge
jupyter                   1.0.0                      py_2    conda-forge
jupyter_client            5.3.4                    py27_1    conda-forge
jupyter_console           5.2.0                    py27_1    conda-forge
jupyter_core              4.6.3            py27h8c360ce_1    conda-forge
kiwisolver                1.1.0            py27he6710b0_0  
ld_impl_linux-64          2.34                 h53a641e_5    conda-forge
libblas                   3.8.0               16_openblas    conda-forge
libcblas                  3.8.0               16_openblas    conda-forge
libclang                  9.0.1           default_hde54327_0    conda-forge
libffi                    3.2.1             he1b5a44_1007    conda-forge
libgcc-ng                 9.2.0                h24d8f2e_2    conda-forge
libgfortran-ng            7.5.0                hdf63c60_6    conda-forge
libgomp                   9.2.0                h24d8f2e_2    conda-forge
libiconv                  1.15              h516909a_1006    conda-forge
liblapack                 3.8.0               16_openblas    conda-forge
libllvm9                  9.0.1                he513fc3_1    conda-forge
libopenblas               0.3.9                h5ec1e0e_0    conda-forge
libpng                    1.6.37               hed695b0_1    conda-forge
libsodium                 1.0.17               h516909a_0    conda-forge
libstdcxx-ng              9.2.0                hdf63c60_2    conda-forge
libuuid                   2.32.1            h14c3975_1000    conda-forge
libxcb                    1.13              h14c3975_1002    conda-forge
libxkbcommon              0.10.0               he1b5a44_0    conda-forge
libxml2                   2.9.10               hee79883_0    conda-forge
llvm-openmp               10.0.0               hc9558a2_0    conda-forge
markupsafe                1.1.1            py27hdf8410d_1    conda-forge
matplotlib                2.2.5                         1    conda-forge
matplotlib-base           2.2.5            py27h250f245_1    conda-forge
mistune                   0.8.4           py27hdf8410d_1001    conda-forge
mpc                       1.1.0             h04dde30_1007    conda-forge
mpfr                      4.0.2                he80fd80_1    conda-forge
mpmath                    1.1.0                      py_0    conda-forge
nbconvert                 5.6.1                    py27_0    conda-forge
nbformat                  4.4.0                    py27_0    conda-forge
ncurses                   6.1               hf484d3e_1002    conda-forge
notebook                  4.4.1                    py27_0    conda-forge
nspr                      4.25                 he1b5a44_0    conda-forge
nss                       3.47                 he751ad9_0    conda-forge
numpy                     1.16.5           py27h95a1406_0    conda-forge
openssl                   1.1.1g               h516909a_0    conda-forge
packaging                 20.4               pyh9f0ad1d_0    conda-forge
pandas                    0.24.2           py27hb3f55d8_0    conda-forge
pandoc                    2.9.2.1                       0    conda-forge
pandocfilters             1.4.2                      py_1    conda-forge
pathlib2                  2.3.5            py27h8c360ce_1    conda-forge
pcre                      8.44                 he1b5a44_0    conda-forge
pexpect                   4.8.0            py27h8c360ce_1    conda-forge
pickleshare               0.7.5           py27h8c360ce_1001    conda-forge
pip                       20.1.1             pyh9f0ad1d_0    conda-forge
prompt_toolkit            1.0.15                     py_1    conda-forge
pthread-stubs             0.4               h14c3975_1001    conda-forge
ptyprocess                0.6.0                   py_1001    conda-forge
pygments                  2.2.0                    py27_0    conda-forge
pyparsing                 2.4.7              pyh9f0ad1d_0    conda-forge
pyqt                      5.12.3           py27hcca6a23_1    conda-forge
pyqt5-sip                 4.19.18                  pypi_0    pypi
pyqtwebengine             5.12.1                   pypi_0    pypi
pyrsistent                0.14.11          py27h516909a_1    conda-forge
python                    2.7.15          h5a48372_1011_cpython    conda-forge
python-dateutil           2.8.1                      py_0    conda-forge
python_abi                2.7                    1_cp27mu    conda-forge
pytz                      2020.1             pyh9f0ad1d_0    conda-forge
pyzmq                     18.1.1           py27h1768529_0    conda-forge
qt                        5.12.5               hd8c4c69_1    conda-forge
qtconsole                 4.7.4              pyh9f0ad1d_0    conda-forge
qtpy                      1.9.0                      py_0    conda-forge
readline                  8.0                  hf8c457e_0    conda-forge
scandir                   1.10.0           py27hdf8410d_1    conda-forge
scipy                     1.2.1            py27h921218d_2    conda-forge
setuptools                44.0.0                   py27_0  
simplegeneric             0.8.1                      py_1    conda-forge
singledispatch            3.4.0.3               py27_1000    conda-forge
six                       1.15.0             pyh9f0ad1d_0    conda-forge
sqlite                    3.30.1               hcee41ef_0    conda-forge
subprocess32              3.5.4            py27h516909a_0    conda-forge
sympy                     1.5.1            py27h8c360ce_3    conda-forge
terminado                 0.8.3            py27h8c360ce_1    conda-forge
testpath                  0.4.4                      py_0    conda-forge
tk                        8.6.10               hed695b0_0    conda-forge
tornado                   4.5.3           py27h14c3975_1001    conda-forge
traitlets                 4.3.3            py27h8c360ce_1    conda-forge
wcwidth                   0.2.4              pyh9f0ad1d_0    conda-forge
weave                     0.17.0           py27h9de70de_2    conda-forge
webencodings              0.5.1                      py_1    conda-forge
wheel                     0.34.2                     py_1    conda-forge
widgetsnbextension        3.5.1                    py27_0    conda-forge
xorg-libxau               1.0.9                h14c3975_0    conda-forge
xorg-libxdmcp             1.1.3                h516909a_0    conda-forge
xz                        5.2.5                h516909a_0    conda-forge
zeromq                    4.3.2                he1b5a44_2    conda-forge
zlib                      1.2.11            h516909a_1006    conda-forge
```

</p>
</details>

Edit: Same error for python 3.6 and the following packages:
<details>
  <summary>Click to get installed packages info</summary>
  <p>

```
_libgcc_mutex             0.1                 conda_forge    conda-forge
_openmp_mutex             4.5                      1_llvm    conda-forge
attrs                     19.3.0                     py_0    conda-forge
backcall                  0.1.0                      py_0    conda-forge
binutils_impl_linux-64    2.34                 h53a641e_5    conda-forge
binutils_linux-64         2.34                hc952b39_20    conda-forge
bleach                    3.1.5              pyh9f0ad1d_0    conda-forge
brian2                    2.3.0.2          py36hdb11119_0    conda-forge
ca-certificates           2020.4.5.2           hecda079_0    conda-forge
certifi                   2020.4.5.2       py36h9f0ad1d_0    conda-forge
cycler                    0.10.0                     py_2    conda-forge
cython                    0.29.20          py36h831f99a_0    conda-forge
dbus                      1.13.6               he372182_0    conda-forge
decorator                 4.4.2                      py_0    conda-forge
defusedxml                0.6.0                      py_0    conda-forge
entrypoints               0.3             py36h9f0ad1d_1001    conda-forge
environment-kernels       1.1.1                    pypi_0    pypi
expat                     2.2.9                he1b5a44_2    conda-forge
fastcache                 1.1.0            py36h8c4c3a4_1    conda-forge
fontconfig                2.13.1            h86ecdb6_1001    conda-forge
freetype                  2.10.2               he06d7ca_0    conda-forge
future                    0.18.2           py36h9f0ad1d_1    conda-forge
gcc_impl_linux-64         7.5.0                hd420e75_6    conda-forge
gcc_linux-64              7.5.0               h09487f9_20    conda-forge
gettext                   0.19.8.1          hc5be6a0_1002    conda-forge
glib                      2.64.3               h6f030ca_0    conda-forge
gmp                       6.2.0                he1b5a44_2    conda-forge
gmpy2                     2.1.0b1          py36h04dde30_0    conda-forge
gsl                       2.6                  h294904e_0    conda-forge
gst-plugins-base          1.14.5               h0935bb2_2    conda-forge
gstreamer                 1.14.5               h36ae1b5_2    conda-forge
gxx_impl_linux-64         7.5.0                hdf63c60_6    conda-forge
gxx_linux-64              7.5.0               h09487f9_20    conda-forge
icu                       64.2                 he1b5a44_1    conda-forge
importlib-metadata        1.6.1            py36h9f0ad1d_0    conda-forge
importlib_metadata        1.6.1                         0    conda-forge
ipykernel                 5.3.0            py36h95af2a2_0    conda-forge
ipython                   7.15.0           py36h9f0ad1d_0    conda-forge
ipython_genutils          0.2.0                      py_1    conda-forge
ipywidgets                7.5.1                      py_0    conda-forge
jedi                      0.17.0           py36h9f0ad1d_0    conda-forge
jinja2                    2.11.2             pyh9f0ad1d_0    conda-forge
jpeg                      9d                   h516909a_0    conda-forge
jsonschema                3.2.0            py36h9f0ad1d_1    conda-forge
jupyter                   1.0.0                      py_2    conda-forge
jupyter_client            6.1.3                      py_0    conda-forge
jupyter_console           6.1.0                      py_1    conda-forge
jupyter_core              4.6.3            py36h9f0ad1d_1    conda-forge
kiwisolver                1.2.0            py36hdb11119_0    conda-forge
ld_impl_linux-64          2.34                 h53a641e_5    conda-forge
libblas                   3.8.0               16_openblas    conda-forge
libcblas                  3.8.0               16_openblas    conda-forge
libclang                  9.0.1           default_hde54327_0    conda-forge
libffi                    3.2.1             he1b5a44_1007    conda-forge
libgcc-ng                 9.2.0                h24d8f2e_2    conda-forge
libgfortran-ng            7.5.0                hdf63c60_6    conda-forge
libgomp                   9.2.0                h24d8f2e_2    conda-forge
libiconv                  1.15              h516909a_1006    conda-forge
liblapack                 3.8.0               16_openblas    conda-forge
libllvm9                  9.0.1                he513fc3_1    conda-forge
libopenblas               0.3.9                h5ec1e0e_0    conda-forge
libpng                    1.6.37               hed695b0_1    conda-forge
libsodium                 1.0.17               h516909a_0    conda-forge
libstdcxx-ng              9.2.0                hdf63c60_2    conda-forge
libuuid                   2.32.1            h14c3975_1000    conda-forge
libxcb                    1.13              h14c3975_1002    conda-forge
libxkbcommon              0.10.0               he1b5a44_0    conda-forge
libxml2                   2.9.10               hee79883_0    conda-forge
llvm-openmp               10.0.0               hc9558a2_0    conda-forge
markupsafe                1.1.1            py36h8c4c3a4_1    conda-forge
matplotlib                3.2.1                         0    conda-forge
matplotlib-base           3.2.1            py36hb8e4980_0    conda-forge
mistune                   0.8.4           py36h8c4c3a4_1001    conda-forge
mpc                       1.1.0             h04dde30_1007    conda-forge
mpfr                      4.0.2                he80fd80_1    conda-forge
mpmath                    1.1.0                      py_0    conda-forge
nbconvert                 5.6.1            py36h9f0ad1d_1    conda-forge
nbformat                  5.0.6                      py_0    conda-forge
ncurses                   6.1               hf484d3e_1002    conda-forge
notebook                  6.0.3            py36h9f0ad1d_0    conda-forge
nspr                      4.25                 he1b5a44_0    conda-forge
nss                       3.47                 he751ad9_0    conda-forge
numpy                     1.18.5           py36h7314795_0    conda-forge
openssl                   1.1.1g               h516909a_0    conda-forge
packaging                 20.4               pyh9f0ad1d_0    conda-forge
pandas                    1.0.4            py36h830a2c2_0    conda-forge
pandoc                    2.9.2.1                       0    conda-forge
pandocfilters             1.4.2                      py_1    conda-forge
parso                     0.7.0              pyh9f0ad1d_0    conda-forge
pcre                      8.44                 he1b5a44_0    conda-forge
pexpect                   4.8.0            py36h9f0ad1d_1    conda-forge
pickleshare               0.7.5           py36h9f0ad1d_1001    conda-forge
pip                       20.1.1                     py_1    conda-forge
prometheus_client         0.8.0              pyh9f0ad1d_0    conda-forge
prompt-toolkit            3.0.5                      py_0    conda-forge
prompt_toolkit            3.0.5                         0    conda-forge
pthread-stubs             0.4               h14c3975_1001    conda-forge
ptyprocess                0.6.0                   py_1001    conda-forge
pygments                  2.6.1                      py_0    conda-forge
pyparsing                 2.4.7              pyh9f0ad1d_0    conda-forge
pyqt                      5.12.3           py36haa643ae_3    conda-forge
pyqt5-sip                 4.19.18                  pypi_0    pypi
pyqtchart                 5.12                     pypi_0    pypi
pyqtwebengine             5.12.1                   pypi_0    pypi
pyrsistent                0.16.0           py36h8c4c3a4_0    conda-forge
python                    3.6.10          h8356626_1011_cpython    conda-forge
python-dateutil           2.8.1                      py_0    conda-forge
python_abi                3.6                     1_cp36m    conda-forge
pytz                      2020.1             pyh9f0ad1d_0    conda-forge
pyzmq                     19.0.1           py36h9947dbf_0    conda-forge
qt                        5.12.5               hd8c4c69_1    conda-forge
qtconsole                 4.7.4              pyh9f0ad1d_0    conda-forge
qtpy                      1.9.0                      py_0    conda-forge
readline                  8.0                  hf8c457e_0    conda-forge
scipy                     1.4.1            py36h2d22cac_3    conda-forge
send2trash                1.5.0                      py_0    conda-forge
setuptools                47.3.0           py36h9f0ad1d_0    conda-forge
six                       1.15.0             pyh9f0ad1d_0    conda-forge
sqlite                    3.30.1               hcee41ef_0    conda-forge
sympy                     1.6              py36h9f0ad1d_0    conda-forge
terminado                 0.8.3            py36h9f0ad1d_1    conda-forge
testpath                  0.4.4                      py_0    conda-forge
tk                        8.6.10               hed695b0_0    conda-forge
tornado                   6.0.4            py36h8c4c3a4_1    conda-forge
traitlets                 4.3.3            py36h9f0ad1d_1    conda-forge
wcwidth                   0.2.4              pyh9f0ad1d_0    conda-forge
webencodings              0.5.1                      py_1    conda-forge
wheel                     0.34.2                     py_1    conda-forge
widgetsnbextension        3.5.1                    py36_0    conda-forge
xorg-libxau               1.0.9                h14c3975_0    conda-forge
xorg-libxdmcp             1.1.3                h516909a_0    conda-forge
xz                        5.2.5                h516909a_0    conda-forge
zeromq                    4.3.2                he1b5a44_2    conda-forge
zipp                      3.1.0                      py_0    conda-forge
zlib                      1.2.11            h516909a_1006    conda-forge
```

</p>
</details>

**Comment by mstimberg** [comment]
Thanks for the report, I can reproduce the problem on my machine. I'll try to look into this in detail soon. Until then you can convert the number to an integer explicitly using the `int` function:
```Python
      eqs = 'dv/dt = (150*Mohm)/(15*ms) * I(t, int(' + str(layer_id * num_neurons_per_layer) + ' + i)) : volt'
```

**Comment by spokli** [comment]
Thanks for that suggestion, explicit typecasting works.
