### ISSUE TITLE
brian2-2.4.2 installing and running appear a ValueError

### ISSUE THREAD

**Issue by Grase04** [brian-team/brian2#1282]
My version of brian2 is 2.4.2, When I run the 'More complex connectivity' in 'Introduction to Brian part 2: Synapses', a ValueError occurred . I didn 't know why? Can you help me?  
Traceback (most recent call last):
  File "…\More complex connectivity.PY", line 7, in <module>  S.connect(condition='i!=j', p=0.2)
  File "…\brian2\core\base.py", line 276, in device_override_decorated_function return func(*args, **kwds)
  File "…\brian2\synapses\synapses.py", line 1400, in connect  namespace=namespace, level=level+2)
  File "…\brian2\synapses\synapses.py", line 1701, in _add_synapses_generator run_namespace=namespace)
  File "…\brian2\codegen\codeobject.py", line 210, in create_runner_codeobj  codeobj_class = device.code_object_class(group.codeobj_class)
  File "…\brian2\devices\device.py", line 266, in code_object_class " one of %s" % (codeobj_class, targets))

ValueError: Unknown code generation target:  numpy , should be  one of ['auto', 'numpy', 'cython']

I have tried to change my version of brian2 to 2.2.1, but it doesn't work.

**Comment by mstimberg** [comment]
Since you closed the issue can we assume that you no longer have the problem?
