### ISSUE TITLE
PopulationRateMonitor does not work when instantiated in a list

### ISSUE THREAD

**Issue by schmitts** [brian-team/brian2#1329]
Running the following script with Brian2 2.4.2

```python
#!/usr/bin/env python3

from brian2 import ms, NeuronGroup, PopulationRateMonitor, defaultclock, run, second

neuron = NeuronGroup(1, "dv/dt = (0 - v)/(10*ms) : 1 (unless refractory)", threshold='v > 1', reset='v = -1', method='euler', refractory=1*ms)
M_rate = [PopulationRateMonitor(neuron)]

duration = 1*second
run(duration)

M_rate[0].smooth_rate(width=100*ms)
```

fails with

```console
Traceback (most recent call last):
  File "./test_population_rate_monitor.py", line 11, in <module>
    M_rate[0].smooth_rate(width=100*ms)
  File "/home/sschmitt/programme/brian2/venv/lib/python3.8/site-packages/brian2/units/fundamentalunits.py", line 2434, in new_f
    result = f(*args, **kwds)
  File "/home/sschmitt/programme/brian2/venv/lib/python3.8/site-packages/brian2/monitors/ratemonitor.py", line 161, in smooth_rate
    return Quantity(np.convolve(self.rate_,
  File "<__array_function__ internals>", line 5, in convolve
  File "/home/sschmitt/programme/brian2/venv/lib/python3.8/site-packages/numpy/core/numeric.py", line 848, in convolve
    raise ValueError('v cannot be empty')
ValueError: v cannot be empty
```

This does not happen when having the rate monitor as a plain variable and not in a list.

[brian_debug_76slapzh.log](https://github.com/brian-team/brian2/files/6915964/brian_debug_76slapzh.log)
[brian_script_a3u6i2tz.py.gz](https://github.com/brian-team/brian2/files/6915966/brian_script_a3u6i2tz.py.gz)

**Comment by Vigneswaran-Chandrasekaran** [comment]
Hi, I think it is because [MagicNetwork](https://brian2.readthedocs.io/en/stable/reference/brian2.core.magic.MagicNetwork.html) object does not add non-Brian objects (like `list`), If you want to add a list specifically, you can explicitly call `Network` and add to it,

```python
neuron = NeuronGroup(. . .)
M_rate = [PopulationRateMonitor(neuron)]
net = Network(neuron, M_rate)
. . .
net.run(duration)
M_rate[0].smooth_rate(width=100*ms)
```

**Comment by thesamovar** [comment]
That's right! Closing this issue.
