### ISSUE TITLE
Using a `SpikeMonitor` on a `NeuronGroup` without `threshold` condition fails uninformatively

### ISSUE THREAD

**Issue by denisalevi** [brian-team/brian2#1337]
```python
from brian2 import *
counter = NeuronGroup(1, 'count : 1')
spike_mon = SpikeMonitor(counter)
run(0*second)
```
fails with
```
|| [python test_spikes_after_deactivating_with_circular_eventspace.py]
|| ERROR      Brian 2 encountered an unexpected error. If you think this is a bug in Brian 2, please report this issue either to the discourse forum at <http://brian.discourse.group/>, or to the issue tracker at <https://github.com/brian-team/brian2/issues>. Please include this file with debug information in your report: /tmp/brian_debug_d_kcgzf0.log  Additionally, you can also include a copy of the script that was run, available at: /tmp/brian_script_o7j460pn.py Thanks! [brian2]
|| Traceback (most recent call last):
||   File "/home/denis/tubcloud/home/projects/brian2cuda/dev/tests/brian2cuda/test_network/test_spikes_after_deactivating_with_circular_eventspace.py", line 40, in <module>
||     spike_mon1 = SpikeMonitor(counter)
||   File "/home/denis/tubcloud/home/projects/brian2cuda/brian2cuda_repository/frozen_repos/brian2/brian2/monitors/spikemonitor.py", line 420, in __init__
||     super(SpikeMonitor, self).__init__(source, event='spike',
||   File "/home/denis/tubcloud/home/projects/brian2cuda/brian2cuda_repository/frozen_repos/brian2/brian2/monitors/spikemonitor.py", line 77, in __init__
||     parent_obj = source.thresholder[event]
|| KeyError: 'spike'
|| [Finished in 2 seconds with code 1]
```
Should this raise something like "Can't record spikes from neurons without threshold condition"?

**Comment by mstimberg** [comment]
It certainly should! I think we have the same error message when you try to use `Synapses` with `on_pre` on a group without a threshold.
