### ISSUE TITLE
"python setup.py install" error

### ISSUE THREAD

**Issue by daoketezzu** [brian-team/brian2#1448]
Traceback (most recent call last):
  File "setup.py", line 128, in <module>
    version=versioneer.get_version(),
  File "<string>", line 1800, in get_version
  File "<string>", line 1732, in get_versions
  File "<string>", line 396, in get_config_from_root
  File "D:\Anaconda3\envs\SNN_simulator\lib\configparser.py", line 780, in get
    d = self._unify_values(section, vars)
  File "D:\Anaconda3\envs\SNN_simulator\lib\configparser.py", line 1146, in _unify_values
    raise NoSectionError(section) from None
configparser.NoSectionError: No section: 'versioneer'

**Comment by mstimberg** [comment]
Hi @daoketezzu . Using `python setup.py install` is [no longer the recommended way to install from source](https://blog.ganssle.io/articles/2021/10/setup-py-deprecated.html) – please use `python -m pip install .` instead. Also see our documentation for other ways to [install the latest development version](https://brian2.readthedocs.io/en/latest/introduction/install.html#development-install).

PS:  I noticed another, unrelated, packaging issue in the github repository recently – make sure you use the most recent version.
