### ISSUE TITLE
Importing brian2 not working on Mac OS X 10.11.3 - (Anaconda distribution)

### ISSUE THREAD

**Issue by sudoankit** [brian-team/brian2#648]
I installed `brian2` through `conda`, and while importing it gives out the following error.

```
>>> import brian2
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "//anaconda/lib/python2.7/site-packages/brian2/__init__.py", line 37, in <module>
    from pylon import *
  File "//anaconda/lib/python2.7/site-packages/pylab.py", line 1, in <module>
    from matplotlib.pylab import *
  File "//anaconda/lib/python2.7/site-packages/matplotlib/__init__.py", line 1131, in <module>
    rcParams = rc_params()
  File "//anaconda/lib/python2.7/site-packages/matplotlib/__init__.py", line 975, in rc_params
    return rc_params_from_file(name, fail_on_error)

  File "//anaconda/lib/python2.7/site-packages/matplotlib/__init__.py", line 1100, in rc_params_from_file
    config_from_file = _rc_params_in_file(name, fail_on_error)
  File "//anaconda/lib/python2.7/site-packages/matplotlib/__init__.py", line 1018, in _rc_params_in_file
    with _open_file_or_url(name) as fd:
  File "//anaconda/lib/python2.7/contextlib.py", line 17, in __enter__
    return self.gen.next()
  File "//anaconda/lib/python2.7/site-packages/matplotlib/__init__.py", line 1000, in _open_file_or_url
    encoding = locale.getdefaultlocale()[1]
  File "//anaconda/lib/python2.7/locale.py", line 543, in getdefaultlocale
    return _parse_localename(locale name
  File "//anaconda/lib/python2.7/locale.py", line 475, in _parse_localename
    raise ValueError, 'unknown locale: %s' % locale name
ValueError: unknown locale: UTF-8
```

But, when `pip` is used  to install `brian2`, the importing works smoothly.

**Comment by mstimberg** [comment]
Hi, thanks for letting us know about this. The issue is not in Brian itself, but it is a bug in Mac OSX with anaconda, here are some instructions to work around it: http://conda.pydata.org/docs/troubleshooting.html#unknown-locale

**Comment by sudoankit** [comment]
Yeah, thanks a lot.
It works now, although you have to manually set `export LANG=en_US.UTF-8` in bashrc.
