### ISSUE TITLE
Unhelpful error message for syntax error in jupyter notebook

### ISSUE THREAD

**Issue by mstimberg** [brian-team/brian2#964]
The following code (note the spurious backtick in the threshold argument), raises a very unhelpful error in the jupyter notebook:
```Python
from brian2 import *
g = NeuronGroup(1, '', threshold='`False')
run(0*ms)
```
Error message:
```
  File "<string>", line unknown
BrianObjectException
```

When running the same code in a script, the error is very verbose but correctly points to the issue:
```
Traceback (most recent call last):
  File "err_test.py", line 5, in <module>
    run(0*ms)
  File "/home/marcel/programming/brian2/brian2/units/fundamentalunits.py", line 2360, in new_f
    result = f(*args, **kwds)
  File "/home/marcel/programming/brian2/brian2/core/magic.py", line 371, in run
    namespace=namespace, profile=profile, level=2+level)
  File "/home/marcel/programming/brian2/brian2/core/magic.py", line 231, in run
    namespace=namespace, profile=profile, level=level+1)
  File "/home/marcel/programming/brian2/brian2/core/base.py", line 278, in device_override_decorated_function
    return func(*args, **kwds)
  File "/home/marcel/programming/brian2/brian2/units/fundamentalunits.py", line 2360, in new_f
    result = f(*args, **kwds)
  File "/home/marcel/programming/brian2/brian2/core/network.py", line 951, in run
    self.before_run(namespace)
  File "/home/marcel/programming/brian2/brian2/core/base.py", line 278, in device_override_decorated_function
    return func(*args, **kwds)
  File "/home/marcel/programming/brian2/brian2/core/network.py", line 843, in before_run
    raise brian_object_exception("An error occurred when preparing an object.", obj, ex)
BrianObjectException: Original error and traceback:
Traceback (most recent call last):
  File "/home/marcel/programming/brian2/brian2/core/network.py", line 841, in before_run
    obj.before_run(run_namespace)
  File "/home/marcel/programming/brian2/brian2/groups/group.py", line 1093, in before_run
    self.update_abstract_code(run_namespace=run_namespace)
  File "/home/marcel/programming/brian2/brian2/groups/neurongroup.py", line 267, in update_abstract_code
    if not is_boolean_expression(code, variables):
  File "/home/marcel/programming/brian2/brian2/parsing/expressions.py", line 64, in is_boolean_expression
    mod = ast.parse(expr, mode='eval')
  File "/home/marcel/anaconda2/envs/brian2/lib/python2.7/ast.py", line 37, in parse
    return compile(source, filename, mode, PyCF_ONLY_AST)
  File "<unknown>", line 1
    `False
         ^
SyntaxError: unexpected EOF while parsing

Error encountered with object named "neurongroup_thresholder".
Object was created here (most recent call only, full details in debug log):
  File "err_test.py", line 3, in <module>
    g = NeuronGroup(1, '', threshold='`False')

An error occurred when preparing an object.   File "<unknown>", line 1

    `False

         ^

SyntaxError: unexpected EOF while parsing
(See above for original error message and traceback.)
```

Originally reported by Eve Armstrong on the [mailing list](https://groups.google.com/d/topic/briansupport/pgZhWdRZ8Oo/discussion).

**Comment by mstimberg** [comment]
I looked a bit into this, and it seems to be an issue with `ipython` (you see the same problem in an `ipython` console) and the fact that it is a `SyntaxError`. I think `ipython` handles `SyntaxError`s differently from other errors to display them more nicely, but I did not find the code responsible for it with a quick search.

We currently create a new `DerivedBrianObjectException` class that derives both from `BrianObjectException` and from the exception class that it encapsulates. If I remove this mechanism (i.e. raise just a `BrianObjectException`), then the error message is displayed fine. We added this double inheritance mechanism so that we don't break code that does `try`/`except` with a specific exception class. I don't think users would want to catch `SyntaxError` exceptions in this way, though, so maybe we should special case this and not derive from `SyntaxError`?

**Comment by thesamovar** [comment]
Writers of a third party library might want to catch syntax errors in user-provided code.

**Comment by thesamovar** [comment]
We could have a new ``BrianSyntaxError`` class, but I'm not sure I'd advocate that for this bug (which seems like an issue with ipython more than brian).

**Comment by mstimberg** [comment]
I agree. I just saw that part of the problem is that according to the docs of `SyntaxError`:

> Instances of this class have attributes filename, lineno, offset and text for easier access to the details.

If I manually add them to our object, the error message gets slightly more helpful:
```
  File "<unknown>", line 1
    `False
         ^
BrianObjectException
```

Maybe we should copy over all exception attributes by default?

**Comment by mstimberg** [comment]
For the record, the place in the ipython code to look for is very likely: https://github.com/ipython/ipython/blob/master/IPython/core/ultratb.py

**Comment by thesamovar** [comment]
Yeah copying them over seems like a good idea if nothing else.
