### ISSUE TITLE
NotImplementedError

### ISSUE THREAD

**Issue by JakenCool** [brian-team/brian2#986]
I tried to run a brian2genn example on HPC and encountered such problem:

Traceback (most recent call last):
  File "/gpfsnyu/packages/anaconda3/4.0.0/lib/python3.5/site-packages/brian2/devices/device.py", line 295, in code_object
    value.implementations[codeobj_class]
  File "/gpfsnyu/packages/anaconda3/4.0.0/lib/python3.5/site-packages/brian2/core/functions.py", line 312, in __getitem__
    keys=keys))
KeyError: 'No implementation available for target genn. Available implementations: cpp, cython, numpy'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "./test.py", line 30, in <module>
    run(duration)
  File "/gpfsnyu/packages/anaconda3/4.0.0/lib/python3.5/site-packages/brian2/units/fundamentalunits.py", line 2375, in new_f
    result = f(*args, **kwds)
  File "/gpfsnyu/packages/anaconda3/4.0.0/lib/python3.5/site-packages/brian2/core/magic.py", line 371, in run
    namespace=namespace, profile=profile, level=2+level)
  File "/gpfsnyu/packages/anaconda3/4.0.0/lib/python3.5/site-packages/brian2/core/magic.py", line 231, in run
    namespace=namespace, profile=profile, level=level+1)
  File "/gpfsnyu/packages/anaconda3/4.0.0/lib/python3.5/site-packages/brian2/core/base.py", line 276, in device_override_decorated_function
    return getattr(curdev, name)(*args, **kwds)
  File "/gpfsnyu/packages/anaconda3/4.0.0/lib/python3.5/site-packages/brian2genn/device.py", line 1571, in network_run
    level=level + 1)
  File "/gpfsnyu/packages/anaconda3/4.0.0/lib/python3.5/site-packages/brian2/devices/cpp_standalone/device.py", line 1299, in network_run
    self.build(direct_call=False, **self.build_options)
  File "/gpfsnyu/packages/anaconda3/4.0.0/lib/python3.5/site-packages/brian2genn/device.py", line 711, in build
    self.process_neuron_groups(neuron_groups, objects)
  File "/gpfsnyu/packages/anaconda3/4.0.0/lib/python3.5/site-packages/brian2genn/device.py", line 1137, in process_neuron_groups
    override_conditional_write=combined_override_conditional_write,
  File "/gpfsnyu/packages/anaconda3/4.0.0/lib/python3.5/site-packages/brian2/devices/cpp_standalone/device.py", line 552, in code_object
    override_conditional_write=override_conditional_write,
  File "/gpfsnyu/packages/anaconda3/4.0.0/lib/python3.5/site-packages/brian2/devices/device.py", line 302, in code_object
    '%s: %s') % (varname, ex))
NotImplementedError: Cannot use function timestep: 'No implementation available for target genn. Available implementations: cpp, cython, numpy'

How should i deal with it?

**Comment by mstimberg** [comment]
Sorry, did we never reply to this? We need to make a new Brian2GeNN release to be compatible with the latest Brian2 version, see brian-team/brian2genn#63
